In [1]:
import numpy as np

In [5]:
# Create a 1D array of numbers from 0 to 9
HLT1darray=np.array([0,1,2,3,4,5,6,7,8,9])
print(HLT1darray)


[0 1 2 3 4 5 6 7 8 9]


In [12]:
#Create a 3×3 NumPy array of all Boolean value Trues
#HLTBooleanarray = np.full((3, 3), True, dtype=bool)
HLTBooleanarray = np.full((3, 3), True)
print(HLTBooleanarray)
#either works)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [14]:
#Extract all odd numbers from array of 1-10
HLT1darray2=np.array([1,2,3,4,5,6,7,8,9,10])
OddArray=np.arange (1,10,2)
print(OddArray)


[1 3 5 7 9]


In [18]:
#Replace all odd numbers in an array of 1-10 with the value -1
#HLT1darray3=np.array([1,2,3,4,5,6,7,8,9,10])
HLT1darray3=np.arange (1,11,1)
print(HLT1darray3)
HLT1darray3[HLT1darray3%2==1]=-1
print(HLT1darray3)


[ 1  2  3  4  5  6  7  8  9 10]
[-1  2 -1  4 -1  6 -1  8 -1 10]


In [27]:
#Convert a 1D array to a 2D array with 2 rows
HLT1darray4=np.arange (1,15,1)
print(HLT1darray4)
HLT1darray5=HLT1darray4.reshape(2,7)
HLT1darray6=np.arange(1,15,1).reshape(2,7)
#print('HLT1darray6 = ',HLT1darray6)
print(HLT1darray5)
print(HLT1darray6)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
#Create two arrays a and b, stack these two arrays vertically use the np.dot and 
#np.sum to calculate totals
aArray = np.arange (1,19).reshape (6,3) 
print(aArray)
bArray = np.arange (19,37).reshape (3,6) 
print(bArray)
cArray = np.dot(aArray, bArray)
print(cArray)
sumArray=np.sum(cArray)
print(sumArray)
sumColArray = np.sum(cArray,axis = 0)
print(sumColArray)
sumRowArray = np.sum(cArray,axis = 1)
print(sumRowArray)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 162  168  174  180  186  192]
 [ 387  402  417  432  447  462]
 [ 612  636  660  684  708  732]
 [ 837  870  903  936  969 1002]
 [1062 1104 1146 1188 1230 1272]
 [1287 1338 1389 1440 1491 1542]]
28647
[4347 4518 4689 4860 5031 5202]
[1062 2547 4032 5517 7002 8487]


In [45]:
#Create the following pattern without hardcoding. Use only NumPy functions.
##[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
n = 0
PatternArr = np.array([n+1, n+1, n+1, n+2, n+2, n+2, n+3, n+3, n+3, n+1, n+2, n+3, n+1, n+2, n+3,n+1, n+2, n+3])
print(PatternArr)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [71]:
 #In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) – remove all repeating items present in array b
aArray2 = np.arange (1,6)
print(aArray2)
bArray2 = np.arange (4,10)
print(bArray2)
cArray2 = np.setdiff1d(aArray2,bArray2)
print(cArray2)
bArray3 = np.delete(bArray2, [0,1])
print(bArray3)
dArray = np.concatenate((aArray2,bArray3),axis = 0)
print(dArray)
eArray = dArray[2]+dArray[3]+dArray[4]+dArray[5]+dArray[6] # Sum up all values in column 5.
print(eArray)

[1 2 3 4 5]
[4 5 6 7 8 9]
[1 2 3]
[6 7 8 9]
[1 2 3 4 5 6 7 8 9]
25
